# Generated by Django 3.0.6 on 2020-05-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200528_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=70)),
                ('phone', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='contact',
        ),
    ]
