# Generated by Django 3.0.6 on 2020-06-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_trackerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuserproductorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
